config/routes.rb
Findtutor::Application.routes.draw do
  
  resources :availabilities

  resources :subadmins do
    collection do
      get "generate_free_code"
    end
  end

  resources :departments


  resources :users do
    collection do
      get 'fetch_departments'
    end
  end


  resources :tutor_locations
  resources :universities

  get 'meetings/joinmeeting'
  get 'meetings/createmeeting'
  post 'meetings/ipn_notification'
  get 'meetings/ipn_notification'
  get 'meetings/canceled_payment_request'
  get 'meetings/completed_payment_request'
  post 'meetings/payment'
  get 'meetings/payment_made'
  post 'tutors/addtutor'
  get 'tutors/addtutor'
  get 'tutors/mgmt'
  get 'tutors/approve'
  get 'subjects_tutors/select'
  
  resources :superadmins
  
  resources :tutor_availabilities
  resources :subjects_tutors

  resources :subjects

  get "admin/login"
  post "admin/login"
  get "admin/logout"

  resources :tutors
  

  resources :meetings do
    collection do
      get 'new_meeting'
      get 'end_meeting'
      post 'create_meeting'
    end
  end

  resources :journals do
    collection do
      get 'add_video_to'
    end
  end

  match 'register' => 'users#register'

  match '/payment_transaction' => 'admin#show_payments_transactions'
  match '/admins/search_payments_transactions' => "admin#search_payments_transactions"

  match '/student_report' => 'admin#show_student_meetings_reports'
  match '/admins/search_student_meetings_reports' => "admin#search_student_meetings_reports"

  match '/tutor_report' => 'admin#show_tutor_meetings_reports'
  match '/admins/search_tutor_meetings_reports' => "admin#search_tutor_meetings_reports"

  match '/meetings/completed_payment' => 'meetings#completed_payment'
  match '/meetings/cancelled_payment' => 'meetings#cancelled_payment'

  match "auth/:provider/callback" => "admin#oauth"

  match "/search_users" => "users#index"

  match "/tutors/mgmt" => "tutors#mgmt"



  match '/reminder_email_before_twelve_hours' => 'cronjobs#reminder_email_before_twelve_hours'
  match '/reminder_email_before_six_hours' => 'cronjobs#reminder_email_before_six_hours'
  match '/reminder_email_before_two_hours' => 'cronjobs#reminder_email_before_two_hours'
  match '/reminder_email_when_meeting_starts' => 'cronjobs#reminder_email_when_meeting_starts'
  match '/reminder_email_when_meeting_ends' => 'cronjobs#reminder_email_when_meeting_ends'










  root :to => 'pages#index'

  match "/about"=>"pages#about"
  match "/faq"=>"pages#faq"
  match "/comingsoon"=>"pages#comingsoon"
  match "/gettingstarted"=>"pages#gettingstarted"
  match "/howtouse"=>"pages#howtouse"
  match "/contact"=>"pages#contact"
  match "/pricing"=>"pages#pricing"
  match "/team"=>"pages#team"
  match "/press"=>"pages#press"
  match "/tos"=>"pages#terms_and_conditions"
  match "edit_user" => "users#edit"


  
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  #protect_from_forgery :except => :ipn_notification
  before_filter :authticate, :except => [:ipn_notification, :show] # to be updated with rails metal method
  
  def authticate
    unless User.find_by_id(session[:user_id])
      flash[:notice] = "Please log in."
      redirect_to :controller => 'admin', :action => 'login'
    end    
  end
  
  # GET /meetings
  # GET /meetings.json
  def index
    @subadmin_meeting = []

    if current_user.present? && current_user.usertype == "superadmin"
      if params[:type] == nil
        @meetings = Meeting.paginate(:page => params[:page], :per_page => 30).order('name')
      elsif params[:type]=='pending' #meeting requested by the current user
        #        @meetings = Meeting.find(:all, :conditions=> ["accept =0 and status = 0"])
        @meetings = Meeting.paginate(:conditions=> ["accept =0 and status = 0"] , :page => params[:page], :per_page => 30).order('name')
      elsif params[:type]=='past'#meeting you attended in the past
        #        @meetings = Meeting.find(:all, :conditions=> ["status >= 3"])
        @meetings = Meeting.paginate(:conditions=> ["status >= 3"] , :page => params[:page], :per_page => 30).order('name')
      elsif params[:type]=='attending' #meeting list that you will be attending(accepted, paid)
        #        @meetings = Meeting.find(:all, :conditions => ['status = ? AND paid = ?', 1, true])
        @meetings = Meeting.paginate(:conditions => ['status = ? AND paid = ?', 1, true] , :page => params[:page], :per_page => 30).order('name')
      elsif params[:type]=='unpaid' #meeting list that you will be attending(accepted, unpaid)
        #        @meetings = Meeting.find(:all, :conditions => ['status = ? AND paid = ?', 1, false])
        @meetings = Meeting.paginate(:conditions => ['status = ? AND paid = ?', 1, false] , :page => params[:page], :per_page => 30).order('name')
      else
        #        @meetings = Meeting.find(:all, :conditions => ['status = ? AND paid = ?', 1, true])
        @meetings = Meeting.paginate(:conditions => ['status = ? AND paid = ?', 1, true], :page => params[:page], :per_page => 30).order('name')
      end
    elsif current_user.present? && current_user.usertype != "superadmin" && current_user.usertype != "subadmin"
      if params[:type] == nil
        #@meetings = Meeting.find(:all, :conditions => ["user_id = ? ", session[:user_id]] )#you are student
        @meetings = Meeting.paginate(:conditions => ["user_id = ? ", session[:user_id]], :page => params[:page], :per_page => 30).order('name')#you are student
      elsif params[:type]=='pending' #meeting requested by the current user
        #        @meetings = Meeting.find(:all, :conditions=> ["accept =0 and status = 0 and (tutor_id = ? or user_id = ?)", session[:tutor_id], session[:user_id]])
        @meetings = Meeting.paginate(:conditions=> ["accept =0 and status = 0 and (tutor_id = ? or user_id = ?)", session[:tutor_id], session[:user_id]], :page => params[:page], :per_page => 30).order('name')
      elsif params[:type]=='past'#meeting you attended in the past
        #        @meetings = Meeting.find(:all, :conditions=> ["(tutor_id = ? OR user_id = ? )and status >= ?", session[:tutor_id], session[:user_id], 3])
        @meetings = Meeting.paginate(:conditions=> ["(tutor_id = ? OR user_id = ? )and status >= ?", session[:tutor_id], session[:user_id], 3], :page => params[:page], :per_page => 30).order('name')
      elsif params[:type]=='attending' #meeting list that you will be attending(accepted, paid)
        #        @meetings = Meeting.find(:all, :conditions => ['(user_id = ? or tutor_id = ?) AND status = ? AND paid = ?', session[:user_id],session[:tutor_id], 1, true])
        @meetings = Meeting.paginate(:conditions => ['(user_id = ? or tutor_id = ?) AND status = ? AND paid = ?', session[:user_id],session[:tutor_id], 1, true], :page => params[:page], :per_page => 30).order('name')
      elsif params[:type]=='unpaid' #meeting list that you will be attending(accepted, unpaid)
        #        @meetings = Meeting.find(:all, :conditions => ['(user_id = ? or tutor_id = ?) AND status = ? AND paid = ?', session[:user_id],session[:tutor_id], 1, false])
        @meetings = Meeting.paginate(:conditions => ['(user_id = ? or tutor_id = ?) AND status = ? AND paid = ?', session[:user_id],session[:tutor_id], 1, false], :page => params[:page], :per_page => 30).order('name')
      else
        #        @meetings = Meeting.find(:all, :conditions => ['(user_id = ? or tutor_id = ?) AND status = ? AND paid = ?', session[:user_id],session[:tutor_id], 1, true])
        @meetings = Meeting.paginate(:conditions => ['(user_id = ? or tutor_id = ?) AND status = ? AND paid = ?', session[:user_id],session[:tutor_id], 1, true], :page => params[:page], :per_page => 30).order('name')
      end
    end

    @subadmin_tutors = []

    if current_user.present? && current_user.usertype=="subadmin"
      Meeting.all.each do |meeting|
        if meeting.tutor.present? && meeting.user.present? && meeting.tutor.user.department == current_user.department && meeting.has_code == true
          @subadmin_meeting << meeting
        end
      end
      @subadmin_meeting = @subadmin_meeting.sort_by { |m| m[:name] }.paginate(:page => params[:page], :per_page => 30)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meetings }
    end
  end

  def end_meeting
    @meeting = Meeting.find_by_id(params[:meeting_id])
    @meeting.update_attribute("status", 3)
    flash[:notice] = "Notice : Meeting status is successfully changed to finished."
    redirect_to :back
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    begin
      @meeting = Meeting.find(params[:id])
      #more code here
    rescue ActiveRecord::RecordNotFound
      redirect_to :action=>"index", :type => "attending"
      return
    end
    
    xml_rsp = Typhoeus::Request.get(@meeting.runningurl).body
    
    if Nokogiri.XML(xml_rsp).xpath('//response/running')[0].content == "true"
      @running = true
    else
      @running = false
    end
    
    
    #if
    #  @meeting.status = 0
    #  @meeting.save
    #end
    
    if !params[:accept].nil? && params[:accept] == '1' && @meeting.tutor_id == session[:tutor_id]
      #only tutor for the meeting can accept the meeting
      @meeting.accept = 1
      @meeting.status = 1# status has further meanings, meeting started 2, meeting completed 2
      if @meeting.has_code
        @meeting.paid = true
      end
      @meeting.save

      UserMailer.tutor_accept_meeting_request(@meeting.id).deliver

      redirect_to @meeting
      return
    elsif !params[:accept].nil? && params[:accept] == '-1' && @meeting.tutor_id == session[:tutor_id]
      # reject meeting request
      @meeting.accept = -1
      @meeting.status = -1
      @meeting.save
      ta = @meeting.tutor_availability
      ta.taken = 0
      ta.save

      UserMailer.tutor_reject_meeting_request(@meeting.id).deliver

      redirect_to @meeting
      return
    elsif !params[:started].nil? && params[:started] == '2' && (@meeting.tutor_id == session[:tutor_id] || @meeting.tutor_id == session[:tutor_id])
      @meeting.status = 2
      @meeting.save
    elsif !params[:finish].nil? && (@meeting.user_id == session[:user_id] || @meeting.tutor_id == session[:tutor_id])
      @meeting.status = 3
      @meeting.save
    elsif !params[:accept].nil? && params[:accept] == '1' && @meeting.tutor_id != session[:tutor_id]
    end
    #puts params.inspect
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new
    @students_subadmin=[]
    @students=[]
    @usr = User.all
    @usr.each do |usr|
      if current_user.present? && current_user.usertype=="subadmin"
        if usr.department.present? && current_user.present? && current_user.department.present? && usr.department == current_user.department && usr.usertype!="subadmin" && usr.usertype!="superadmin" && usr.tutor.blank?
          @students_subadmin << usr
        end
      elsif current_user.present? && current_user.usertype=="superadmin" && usr.usertype!="superadmin" && usr.usertype!="subadmin" && usr.tutor.blank?
        @students << usr
      end
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  def create
    code = FreeCode.find_by_code(params[:code])

    @meeting = Meeting.new(params[:meeting])
    @meeting.attendeePW = rand(36**20).to_s(36)
    @meeting.moderatorPW = rand(36**20).to_s(36)
    
    if current_user.present? && (current_user.usertype == "superadmin" || current_user.usertype == "subadmin")
      @meeting.user_id = params[:user_id]
      @meeting.accept = 1.to_i
      @meeting.status = 1.to_i
    else
      @meeting.user_id = session[:user_id]
      @meeting.status = 0.to_i
    end
    unless code.blank?
      @meeting.has_code = true
    end
    #puts session[:user_id].inspect
    @meeting.name = Subject.find(@meeting.subject_id).title + Time.now.strftime('_%y%m%d%h%m')

    if @meeting.tutor.rate == 0
      @meeting.paid = true
    end

    respond_to do |format|
      if @meeting.save
        ta = TutorAvailability.find(@meeting.tutor_availability_id)
        ta.taken = 1
        ta.save

        if current_user.present? && (!current_user.usertype == "superadmin" || !current_user.usertype == "subadmin")
          UserMailer.student_request_for_meeting_to_tutor(@meeting.id).deliver
        else
          UserMailer.admin_subadmin_create_meeting(@meeting.id, current_user).deliver
        end
        

app/helpers/meetings_helper.rb
module MeetingsHelper
  
  def meetingstatus(i)
    if i == 0
      "initiated"
    elsif i == -1
      "rejected"
    elsif i == 1
      "accepted"
    elsif i == 2
      "paid"
    elsif i == 3
      "started"
    elsif i == 4
      "finished"
    end
  end
  
  def meetingheader
    case params[:type]
    when 'pending'
      session[:tutor_id]? 'Received following appointment request':'Waiting tutor response'
    when 'past'
      'Past Meetings'
    when 'attending'
      'You will be attending'
    end
    #if params[:type]== 'pending'
    #  session[:tutor_id]? 'Received following appointment request':'Waiting tutor response'
    #elsif  params[:type]=='past'
    #  'Past Meetings'
    #elsif  params[:type]=='attending'
    #  'You will be attending'
    #end
  end
  
  def meetinginfo
    if params[:action] == 'new'
      #to be used at new meeting page
      TutorAvailability.find(params[:avlb_id])
    elsif params[:action] == 'edit'
      @meeting.tutor_availability
    end
  end
  
  def youaretutor
    Meeting.find(:all, :conditions => ['tutor_id = ? AND accept = ? AND status != 3', session[:tutor_id], 1])
  end
  
  def youarestudent
    Meeting.find(:all, :conditions => ['user_id = ? AND accept = ? AND status != 3', session[:user_id], 1])
  end

  def paymentlink
    if @meeting.accept == 1 && @meeting.user_id == session[:user_id] && @meeting.paid == false
      button_to 'pay', :controller => 'meetings', :action => 'payment', :mid=> @meeting.id
    end 
  end
  
  def meeting_status(i)
    if i == 1
      'scheduled'
    elsif i == -1
      'rejected'
    elsif i == 2
      'started'
    elsif i == 3
      'finished'
    else
      'waiting'
    end
  end
  
  def acceptlink
    if @meeting.accept == 0 && @meeting.tutor_id == session[:tutor_id]
      (link_to 'accept', :controller => 'meetings', :action => 'show', :accept=>1) + " | " + (link_to 'reject', :controller => 'meetings', :action => 'show', :accept=>-1)
    end 
  end

end

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% @meeting.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%if params[:action] == 'new'%>
    <%= f.hidden_field :tutor_id, :value => meetinginfo.tutor_id %>
    <%= f.hidden_field :tutor_availability_id, :value => meetinginfo.id %>
    <%if current_user.present? && (current_user.usertype == "superadmin" || current_user.usertype == "subadmin")%>
      <%btntext = "Create Meeting"%>
    <%else%>
      <%btntext = "Request Apointment"%>
    <%end%>
  <%elsif params[:action] == 'edit'%>
    <%btntext = "Update Meeting"%>
    <div class="field">
      <%= f.label 'accept:' %><br />
      <%= f.text_field :accept %>
    </div>
    <div class="field">
      <%= f.label 'paid:' %><br />
      <%= f.text_field :paid %>
    </div>
  <%end%><!--edit test end-->

  <div class="field">
    <%= f.label :subject %><br />
    <%= f.select :subject_id, meetinginfo.tutor.subjs_and_ids %>
  </div>

  <%if current_user.present? && current_user.usertype == "superadmin" %>
    <div class="field">
      <%if controller.action_name == "edit"%>
        <%= f.label :student %><br />
        <%= select_tag 'user_id', options_from_collection_for_select(@students, 'id' , "username")%>
      <%else%>
        <%= f.label :student %><br />
        <%= select_tag 'user_id', options_from_collection_for_select(@students, 'id' , "username") %>
      <%end%>
    </div>
  <%elsif current_user.present? && current_user.usertype == "subadmin"%>
    <div class="field">
      <%if controller.action_name == "edit"%>
        <%= f.label :student %><br />
        <%= select_tag 'user_id', options_from_collection_for_select(@students_subadmin, 'id' , "username"), :disabled => true %>
      <%else%>
        <%= f.label :student %><br />
        <%= select_tag 'user_id', options_from_collection_for_select(@students_subadmin, 'id' , "username")%>
      <%end%>
    </div>
  <%end%>

  <%if meetinginfo.timetype == 1  %><!--face2face meeting-->
    <div class="field">
      <%= f.label :location %><br />
      <%= f.select :location_id, meetinginfo.tutor.user.locations_and_ids %>
    </div>
  <%end%>

  <div class="field">
    <%= f.label 'message to the tutor:' %><br />
    <%= f.text_area :message, :size => "50x8" %>
  </div>

  <div class="field">
    <%= label_tag 'Enter code for free Meeting:' %><br />
    <%= text_field_tag "code", "",:placeholder => "Code" %>
  </div>

  <div class="actions">
    <%= f.submit btntext %>
  </div>
<%end%>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<div id="schedulecontainer">
  <div id="meetinginfo">
    <h3>Meeting Info:</h3>
    Tutor: <%= meetinginfo.tutor.user.fullname %><br />
    Date: <%= meetinginfo.start_time.strftime('%D') %><br />
    Time: <%= meetinginfo.start_time.strftime('%H:%M')%><br />
    Duration: <%= pluralize(meetinginfo.length, 'hour')%><br />
    Tutor Rate: $<%= meetinginfo.tutor.rate%><br />
    Price for this meeting: $<%= meetinginfo.tutor.rate * meetinginfo.length %>
  </div>
  <div id="meetingform">
    <%= render 'form' %>
  </div>
<div class="fix"></div>
</div>
<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<div id="meetingheader">
  <%=meetingheader%>
</div>


<table id="meetinglist" border="1">
  <tr>
    <th>Name</th>
    <th>Start date</th>
    <th>Time</th>
    <th>Length</th>
    <th>Payment</th>
    <th>Subject</th>
    <th>Tutor</th>
    <th>Student</th>
    <th>Response</th>
    <th>Type</th>
  </tr>


  <%if current_user.present? && current_user.usertype!="subadmin" && @meetings.present? && @meetings.length > 0%>

    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= link_to meeting.name, meeting %></td>
        <td><%= meeting.tutor_availability.start_time.strftime("%D")%></td>
        <td>
          <%= meeting.tutor_availability.start_time.strftime("%H:%M %p") %>~<%= meeting.tutor_availability.end_time.strftime("%H:%M %p") %>
        </td>
        <td><%= pluralize(meeting.tutor_availability.length,"hour")%></td>
        <td>
          <%if meeting.paid%>
            paid
          <%else%>
            waiting
          <%end%>
        </td>
        <% if meeting.tutor.present? && meeting.user.present? %>
          <td>
            <% if meeting.subject.present?%>
              <%= Subject.find(meeting.subject).title %>
            <%else%>
              Not Found
            <%end%>
          </td>
          <td>
            <% if meeting.tutor.present? && meeting.tutor.user.present?%>
              <%= link_to meeting.tutor.user.fullname,meeting.tutor.user%>
            <%else%>
              Not Found
            <%end%>
          </td>
          <td>
            <% if meeting.user.present?%>
              <%= link_to meeting.user.fullname, meeting.user%>
            <%else%>
              Not Found
            <%end%>
          </td>
          <td>
            <%= meeting_status(meeting.status) %>
          </td>
          <td>
            <%if !meeting.tutor_availability.blank?%>
              <%= meeting.tutor_availability.timetype == 1? "Face2Face":"Virtual" %>
            <%else%>
              Not Found
            <%end%>
          </td>
          <%if meeting.tutor_id == session[:tutor_id] && meeting.accept == 0 && current_user.present? && current_user.username!="admin"%>
            <td>
              <%= link_to 'accept', :id=> meeting.id, :controller => 'meetings', :action => 'show', :accept=>1%>
            </td>
            <td>
              <%= link_to 'reject', :id=> meeting.id, :controller => 'meetings', :action => 'show', :accept=>-1%>
            </td>
          <%else%>
            <td colspan="2"></td>
          <%end%>
          <%if current_user.present? && current_user.usertype == "superadmin" %>
            <td><%= link_to 'Show', meeting %></td>
            <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
            <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%end%>
        <%else%>
          <td colspan="6">Not Found</td>
          <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
    <%= will_paginate(@meetings) %>
  <%elsif current_user.present? && current_user.usertype=="subadmin"%>
    <%if @subadmin_meeting.present?%>
      <% @subadmin_meeting.each do |meeting|%>
        <tr>
          <td><%= link_to meeting.name, meeting %></td>
          <td><%= meeting.tutor_availability.start_time.strftime("%D")%></td>
          <td>
            <%= meeting.tutor_availability.start_time.strftime("%H:%M %p") %>~<%= meeting.tutor_availability.end_time.strftime("%H:%M %p") %>
          </td>
          <td><%= pluralize(meeting.tutor_availability.length,"hour")%></td>
          <td>
            <%if meeting.paid%>
              paid
            <%else%>
              waiting
            <%end%>
          </td>
          <% if meeting.tutor.present? && meeting.user.present? %>
            <td><%= Subject.find(meeting.subject).title %></td>
            <td>
              <%if meeting.tutor.present? && meeting.tutor.user.present? %>
                <%= link_to meeting.tutor.user.fullname,meeting.tutor.user %>
              <%else%>
                Not Found
              <%end%>
            </td>
            <td>
              <% if meeting.tutor.present? && meeting.tutor.user.present?%>
                <%= link_to meeting.user.fullname, meeting.user %>
              <%else%>
                Not Found
              <%end%>
            </td>
            <td><%= meeting_status(meeting.status) %></td>
            <%if meeting.tutor_id == session[:tutor_id] && meeting.accept == 0 && current_user.present? && current_user.username!="admin"%>
              <td><%= link_to 'accept', :id=> meeting.id, :controller => 'meetings', :action => 'show', :accept=>1%></td>
              <td><%= link_to 'reject', :id=> meeting.id, :controller => 'meetings', :action => 'show', :accept=>-1%></td>
            <%else%>
              <td colspan="2"></td>
            <%end%>
            <td>
              <%if !meeting.tutor_availability.blank?%>
                <%= meeting.tutor_availability.timetype == 1? "Face2Face":"Virtual" %>
              <%end%>
            </td>
            <%if current_user.present? && current_user.usertype == "subadmin"%>
              <td><%= link_to 'Show', meeting %></td>
              <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
          <%#*<td>%>
          <%#= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %>
          <%#*</td>%>
              <td><%= link_to 'Destroy', "https://docs.google.com/spreadsheet/viewform?fromEmail=true&formkey=dGg1UnIyZnlaMFF2LWZpSjE3TWF6R1E6MQ" %></td>
            <%end%>
          <%else%>
            <td colspan="6">
              Not Found
            </td>
            <td><%= link_to 'Destroy', "https://docs.google.com/spreadsheet/viewform?fromEmail=true&formkey=dGg1UnIyZnlaMFF2LWZpSjE3TWF6R1E6MQ" %></td>
          <%end%>
        </tr>
      <%end%>
      <%= will_paginate(@subadmin_meeting) %>
    <%end%>
  <% end %>

</table>

<br />

<%#= link_to 'New Meeting',  new_meeting_meetings_path %>

app/views/meetings/new.html.erb
<h1>Request for meeting</h1>

<div id="schedulecontainer">
  <div id="meetinginfo">
    <h3>Meeting Info:</h3>
    Tutor: <%= meetinginfo.tutor.user.fullname %><br />
    Date: <%= meetinginfo.start_time.strftime('%D') %><br />
    Time: <%= meetinginfo.start_time.strftime('%H:%M')%><br />
    Duration: <%= pluralize(meetinginfo.length, 'hour')%><br />
    Tutor Rate: $<%= meetinginfo.tutor.rate%><br />
    Price for this meeting: $<%= meetinginfo.tutor.rate * meetinginfo.length %>
  </div>
  <div id="meetingform">
    <%= render 'form' %>
  </div>
<div class="fix"></div>
</div>
<%= link_to 'Back', meetings_path %>

app/views/meetings/new_meeting.html.erb
<h1>Request meeting with tutor</h1>
<div id="schedulecontainer">
  <div id="meetingform">
    <%= form_for @meeting, :url => create_meeting_meetings_path(@meeting) do |f|%>
      <% if @meeting.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>
          <ul>
            <% @meeting.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.label :tutor %><br />
        <%= f.select 'tutor_id', options_from_collection_for_select(Tutor.all, 'id' , "id")%>
      </div>
      <div class="field">
        <%= f.label :student %><br />
        <%= select_tag 'user_id', options_from_collection_for_select(@students, 'id' , "username")%>
      </div>

    <div class="field">
        <%= f.label :subject %><br />
        <%= f.select 'subject_id', options_from_collection_for_select(Subject.all, 'id', 'title')%>
      </div>
      <div class="field">
        <%= f.label :location %><br />
        <%= f.select 'location_id', options_from_collection_for_select(TutorLocation.all, 'id', 'name')%>
      </div>
      <div class="field">
        <%= f.label 'message to the tutor:' %><br />
        <%= f.text_area :message, :size => "50x8" %>
      </div>
      <div class="field">
        <%= label_tag 'Enter code for free Meeting:' %><br />
        <%= text_field_tag "code", "",:placeholder => "Code" %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <%end%>
  </div>
  <div class="fix"></div>
</div>
<%= link_to 'Back', meetings_path %>