config/routes.rb
Findtutor::Application.routes.draw do
  
  resources :availabilities

  resources :subadmins do
    collection do
      get "generate_free_code"
    end
  end

  resources :departments


  resources :users do
    collection do
      get 'fetch_departments'
    end
  end


  resources :tutor_locations
  resources :universities

  get 'meetings/joinmeeting'
  get 'meetings/createmeeting'
  post 'meetings/ipn_notification'
  get 'meetings/ipn_notification'
  get 'meetings/canceled_payment_request'
  get 'meetings/completed_payment_request'
  post 'meetings/payment'
  get 'meetings/payment_made'
  post 'tutors/addtutor'
  get 'tutors/addtutor'
  get 'tutors/mgmt'
  get 'tutors/approve'
  get 'subjects_tutors/select'
  
  resources :superadmins
  
  resources :tutor_availabilities
  resources :subjects_tutors

  resources :subjects

  get "admin/login"
  post "admin/login"
  get "admin/logout"

  resources :tutors
  

  resources :meetings do
    collection do
      get 'new_meeting'
      get 'end_meeting'
      post 'create_meeting'
    end
  end

  resources :journals do
    collection do
      get 'add_video_to'
    end
  end

  match 'register' => 'users#register'

  match '/payment_transaction' => 'admin#show_payments_transactions'
  match '/admins/search_payments_transactions' => "admin#search_payments_transactions"

  match '/student_report' => 'admin#show_student_meetings_reports'
  match '/admins/search_student_meetings_reports' => "admin#search_student_meetings_reports"

  match '/tutor_report' => 'admin#show_tutor_meetings_reports'
  match '/admins/search_tutor_meetings_reports' => "admin#search_tutor_meetings_reports"

  match '/meetings/completed_payment' => 'meetings#completed_payment'
  match '/meetings/cancelled_payment' => 'meetings#cancelled_payment'

  match "auth/:provider/callback" => "admin#oauth"

  match "/search_users" => "users#index"

  match "/tutors/mgmt" => "tutors#mgmt"



  match '/reminder_email_before_twelve_hours' => 'cronjobs#reminder_email_before_twelve_hours'
  match '/reminder_email_before_six_hours' => 'cronjobs#reminder_email_before_six_hours'
  match '/reminder_email_before_two_hours' => 'cronjobs#reminder_email_before_two_hours'
  match '/reminder_email_when_meeting_starts' => 'cronjobs#reminder_email_when_meeting_starts'
  match '/reminder_email_when_meeting_ends' => 'cronjobs#reminder_email_when_meeting_ends'










  root :to => 'pages#index'

  match "/about"=>"pages#about"
  match "/faq"=>"pages#faq"
  match "/comingsoon"=>"pages#comingsoon"
  match "/gettingstarted"=>"pages#gettingstarted"
  match "/howtouse"=>"pages#howtouse"
  match "/contact"=>"pages#contact"
  match "/pricing"=>"pages#pricing"
  match "/team"=>"pages#team"
  match "/press"=>"pages#press"
  match "/tos"=>"pages#terms_and_conditions"
  match "edit_user" => "users#edit"


  
end

app/views/admin/login.html.erb
<h1>Login</h1>
<div id="notice"><%=notice%></div>
      <%= form_tag do %>
	<div>
	  <label for="username">Username: </label>
	  <%= text_field_tag :username %>
	</div>
	
	<div>
	  <label for="password">Password:</label>
	  <%= password_field_tag :password %>
	</div>
	
	<div style="float: left;">
	  <%= submit_tag "Login", :style=>"height: 27px; width: 100px;margin-top:2px;" %> or login with
	</div> 
      <div style="float: left;">
	<%=link_to image_tag('ico-footer-facebook.png'), '/auth/facebook'%>
      </div>	
      <% end %>

app/views/admin/logout.html.erb
<h1>Admin#logout</h1>
<p>Find me in app/views/admin/logout.html.erb</p>

app/views/admin/show_payments_transactions.html.erb
<% total_amount = 0 %>

<%unless @trans_free_code.blank?%>
  <h1>Listing SubAdmin Department's Payment Transaction</h1>
  <%if current_user.usertype == "superadmin"%>
    <div>
      <%= form_tag '/admins/search_payments_transactions' do %>
        <p>
          <%= label_tag :subadmin_search , "Please Select a Subadmin to see its transactions"%>
          <%= select_tag "search", options_for_select(Subadmin.all.map{|sub| [sub.user.username, sub.user.id]}), {:prompt => "Please select a subadmin"}%>
          <%= submit_tag "Search", :name => nil %>
        </p>
      <% end %>
    </div>
  <%end%>
  <table>
    <tr>
      <th> Transaction Key</th>
      <th> Tutor </th>
      <th> Student </th>
      <th> Meeting </th>
      <th> Transaction Amount </th>
      <th> Paid amount at</th>
    </tr>

    <%if current_user.usertype == "superadmin"%>
    <%# @trans_free_code = @trans_free_code.first %>
      <%@trans_free_code.each do |trans|%>
        <%#tran.each do |trans|%>
          <tr>
            <%unless trans.pay_key.blank? %>
              <td><%= trans.pay_key %></td>
            <%else%>
              <td>NIL</td>
            <%end%>

            <%if !trans.tutor.blank? && !trans.tutor.user.blank?%>
              <td><%= link_to trans.tutor.user.fname + " " + trans.tutor.user.lname , tutor_path(trans.tutor)%></td>
            <%else%>
              <td>NIL</td>
            <%end%>

            <%unless trans.user.blank? %>
              <td><%= link_to trans.user.fname + " " + trans.user.lname, user_path(trans.user) %></td>
            <%else%>
              <td>NIL</td>
            <%end%>

            <%unless trans.meeting.blank? %>
              <td><%= link_to trans.meeting.name , meeting_path(trans.meeting) %></td>
            <%else%>
              <td>NIL</td>
            <%end%>

            <%unless trans.amount.blank? %>
              <td>
                $
                <%total_amount = total_amount + trans.amount%>
                <%= trans.amount%>
              </td>
            <%else%>
              <td>NIL</td>
            <%end%>

            <%unless trans.created_at.blank? %>
              <td><%= trans.created_at.strftime("%m/%d/%Y at %I:%M %p ") %></td>
            <%else%>
              <td>NIL</td>
            <%end%>
          </tr>
        <%#end%>
      <%end%>
      <%= will_paginate(@trans_free_code , :params => {:search => @search} )%>
    <%end%>
  </table>
<%else%>
  <h1>Listing Payment Transaction</h1>

  <%if current_user.usertype == "superadmin"%>
    <div>
      <%= form_tag '/admins/search_payments_transactions' do %>
        <p>
          <%= label_tag :subadmin_search , "Please Select a Subadmin to see its transactions"%>
          <%= select_tag "search", options_for_select(Subadmin.all.map{|sub| [sub.user.username, sub.user.id]}), {:prompt => "Please select a subadmin"}%>
          <%= submit_tag "Search", :name => nil %>
        </p>
      <% end %>
    </div>
  <%end%>
  <table>
    <tr>
      <th> Transaction Key</th>
      <th> Tutor </th>
      <th> Student </th>
      <th> Meeting </th>
      <th> Transaction Amount </th>
      <th> Paid amount at</th>
    </tr>

    <%if current_user.usertype == "subadmin"%>
      <%unless @trans_subadmin.blank?%>
        <%@trans_subadmin.each do |trans|%>
          <tr>
            <%unless trans.pay_key.blank? %>
              <td><%= trans.pay_key %></td>
            <%else%>
              <td>NIL</td>
            <%end%>

            <%if !trans.tutor.blank? && !trans.tutor.user.blank? %>
              <td><%= link_to trans.tutor.user.fname + " " + trans.tutor.user.lname , tutor_path(trans.tutor)%></td>
            <%else%>
              <td>NIL</td>
            <%end%>

            <%unless trans.user.blank? %>
              <td><%= link_to trans.user.fname + " " + trans.user.lname, user_path(trans.user) %></td>
            <%else%>
              <td>NIL</td>
            <%end%>

            <%unless trans.meeting.blank? %>
              <td><%= link_to trans.meeting.name , meeting_path(trans.meeting) %></td>
            <%else%>
              <td>NIL</td>
            <%end%>

            <%unless trans.amount.blank? %>
              <td>                $
                <%total_amount = total_amount + trans.amount%>
                <%= trans.amount%>
              </td>
            <%else%>
              <td>NIL</td>
            <%end%>

            <%unless trans.created_at.blank? %>
              <td><%= trans.created_at.strftime("%m/%d/%Y at %I:%M %p ") %></td>
            <%else%>
              <td>NIL</td>
            <%end%>
          </tr>
        <%end%>
        <%= will_paginate(@trans_subadmin , :params => {:search => @search} )%>
      <%end%>
    <%else%>
      <%unless @trans.blank?%>
        <%@trans.each do |trans|%>
          <tr>
            <%unless trans.pay_key.blank? %>
              <td><%= trans.pay_key %></td>
            <%else%>
              <td>NIL</td>
            <%end%>

            <%if !trans.tutor.blank? && !trans.tutor.user.blank?%>
              <td><%= link_to trans.tutor.user.fname + " " + trans.tutor.user.lname , tutor_path(trans.tutor)%></td>
            <%else%>
              <td>NIL</td>
            <%end%>

            <%unless trans.user.blank? %>
              <td><%= link_to trans.user.fname + " " + trans.user.lname, user_path(trans.user) %></td>
            <%else%>
              <td>NIL</td>
            <%end%>

            <%unless trans.meeting.blank? %>
              <td><%= link_to trans.meeting.name , meeting_path(trans.meeting) %></td>
            <%else%>
              <td>NIL</td>
            <%end%>

            <%unless trans.amount.blank? %>
              <td>
                $
                <%total_amount = total_amount + trans.amount%>
                <%= trans.amount%>
              </td>
            <%else%>
              <td>NIL</td>
            <%end%>

            <%unless trans.created_at.blank? %>
              <td><%= trans.created_at.strftime("%m/%d/%Y at %I:%M %p ") %></td>
            <%else%>
              <td>NIL</td>
            <%end%>
          </tr>
        <%end%>
        <%= will_paginate(@trans , :params => {:search => @search} )%>
      <% end %>
    <%end%>
  </table>
<%end%>
<br />
Total amount of transactions is $ <%=total_amount %>

app/views/admin/show_student_meetings_reports.html.erb
<% total_paid = 0  %>
<%unless @searched_user_meetings.blank?%>
  <h1>Listing Meetings for Searched User</h1>
  <%if current_user.usertype == "superadmin" || current_user.usertype == "subadmin"%>
    <div>
      <%= form_tag '/admins/search_student_meetings_reports' do %>
        <p>
          <%= label_tag :name , "Enter a first name Or Last name to search for Student"%>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", :name => nil %>
        </p>
      <% end %>
    </div>
  <%end%>
  <table>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>Length</th>
      <th>Payment</th>
      <th>Subject</th>
      <th>Tutor</th>
      <th>Student</th>
      <th>Response</th>
      <th>Amount</th>
    </tr>
    <%if current_user.usertype == "superadmin" || current_user.usertype == "subadmin"%>
      <%@searched_user_meetings.each do |meeting|%>
        <tr>
          <td><%= link_to meeting.name, meeting %></td>
          <td><%= meeting.tutor_availability.start_time.strftime("%D")%></td>
          <td><%= pluralize(meeting.tutor_availability.length,"hour")%></td>
          <td>
            <%if meeting.paid%>
              paid
            <%else%>
              waiting
            <%end%>
          </td>
          <% if  meeting.tutor %>
            <td><%= Subject.find(meeting.subject).title %></td>
            <td><%= link_to meeting.tutor.user.fullname,meeting.tutor.user %> </td>
            <td> <%= link_to meeting.user.fullname, meeting.user %> </td>
            <td><%= meeting_status(meeting.accept) %></td>
            <%if meeting.tutor_id == session[:tutor_id] && meeting.accept == 0 && current_user.username!="admin"%>
              <td><%= link_to 'accept', :id=> meeting.id, :controller => 'meetings', :action => 'show', :accept=>1%></td>
              <td><%= link_to 'reject', :id=> meeting.id, :controller => 'meetings', :action => 'show', :accept=>-1%></td>
            <%else%>
              <td colspan="2"></td>
            <%end%>
          <%else%>
            <td colspan="6"></td>
          <%end%>
          <td>
            $ <% if meeting.user.transaction.present? %>
              <%total_paid = total_paid + meeting.user.transaction.last.amount%>
              <%= meeting.user.transaction.last.amount%>
            <% else %>
              <%= 0.to_f%>
            <%end%>
          </td>
          <td><%= link_to 'Show', meeting %></td>
          <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
          <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <%end%>
      <%= will_paginate(@searched_user_meetings , :params => {:search => @search})%>
    <%end%>
  </table>
  <br />
  Total Paid amount is $<%=total_paid %>
  <br />
<%else%>
  <%if current_user.usertype == "superadmin" || current_user.usertype == "subadmin"%>
    <div>
      <%= form_tag '/admins/search_student_meetings_reports' do %>
        <p>
          <%= label_tag :name , "Enter a first name Or Last name to search to search for Student"%>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", :name => nil %>
        </p>
      <% end %>
    </div>
  <%end%>
  No record found!
<%end%>

app/views/admin/show_tutor_meetings_reports.html.erb
<% total_earning = 0  %>
<%unless @searched_user_meetings.blank?%>
  <h1>Listing Meetings for Searched Tutor</h1>
  <%if current_user.usertype == "superadmin" || current_user.usertype == "subadmin"%>
    <div>
      <%= form_tag '/admins/search_tutor_meetings_reports' do %>
        <p>
          <%= label_tag :name , "Enter a first name Or Last name to search for Tutor"%>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", :name => nil %>
        </p>
      <% end %>
    </div>
  <%end%>
  <table>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>Length</th>
      <th>Payment</th>
      <th>Subject</th>
      <th>Tutor</th>
      <th>Student</th>
      <th>Response</th>
      <th>Amount</th>
    </tr>
    <%if current_user.usertype == "superadmin" || current_user.usertype == "subadmin"%>
      <%@searched_user_meetings.each do |meeting|%>
        <tr>
          <td><%= link_to meeting.name, meeting %></td>
          <td><%= meeting.tutor_availability.start_time.strftime("%D")%></td>
          <td><%= pluralize(meeting.tutor_availability.length,"hour")%></td>
          <td>
            <%if meeting.paid%>
              paid
            <%else%>
              waiting
            <%end%>
          </td>
          <% if  meeting.tutor %>
            <td><%= Subject.find(meeting.subject).title %></td>
            <td><%= link_to meeting.tutor.user.fullname,meeting.tutor.user %> </td>
            <td> <%= link_to meeting.user.fullname, meeting.user %> </td>
            <td><%= meeting_status(meeting.accept) %></td>
            <%if meeting.tutor_id == session[:tutor_id] && meeting.accept == 0 && current_user.username!="admin"%>
              <td><%= link_to 'accept', :id=> meeting.id, :controller => 'meetings', :action => 'show', :accept=>1%></td>
              <td><%= link_to 'reject', :id=> meeting.id, :controller => 'meetings', :action => 'show', :accept=>-1%></td>
            <%else%>
              <td colspan="2"></td>
            <%end%>
          <%else%>
            <td colspan="6"></td>
          <%end%>

          <td>
            $ <% if meeting.user.transaction.present? %>
              <%total_earning = total_earning + meeting.user.transaction.last.amount%>
              <%= meeting.user.transaction.last.amount%>
            <% else%>
              <%= 0.to_f%>
            <%end%>
          </td>
          <td><%= link_to 'Show', meeting %></td>
          <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
          <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <%end%>
      <%= will_paginate(@searched_user_meetings , :params => {:search => @search})%>
    <%end%>
  </table>
  <br />
  Total Earned amount is $<%= total_earning %>
  <br />
<%else%>
  <%if current_user.usertype == "superadmin" || current_user.usertype == "subadmin"%>
    <div>
      <%= form_tag '/admins/search_tutor_meetings_reports' do %>
        <p>
          <%= label_tag :name , "Enter a first name Or Last name to search for Tutor"%>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", :name => nil %>
        </p>
      <% end %>
    </div>
  <%end%>
  No record found!
<%end%>