config/routes.rb
Findtutor::Application.routes.draw do
  
  resources :availabilities

  resources :subadmins do
    collection do
      get "generate_free_code"
    end
  end

  resources :departments


  resources :users do
    collection do
      get 'fetch_departments'
    end
  end


  resources :tutor_locations
  resources :universities

  get 'meetings/joinmeeting'
  get 'meetings/createmeeting'
  post 'meetings/ipn_notification'
  get 'meetings/ipn_notification'
  get 'meetings/canceled_payment_request'
  get 'meetings/completed_payment_request'
  post 'meetings/payment'
  get 'meetings/payment_made'
  post 'tutors/addtutor'
  get 'tutors/addtutor'
  get 'tutors/mgmt'
  get 'tutors/approve'
  get 'subjects_tutors/select'
  
  resources :superadmins
  
  resources :tutor_availabilities
  resources :subjects_tutors

  resources :subjects

  get "admin/login"
  post "admin/login"
  get "admin/logout"

  resources :tutors
  

  resources :meetings do
    collection do
      get 'new_meeting'
      get 'end_meeting'
      post 'create_meeting'
    end
  end

  resources :journals do
    collection do
      get 'add_video_to'
    end
  end

  match 'register' => 'users#register'

  match '/payment_transaction' => 'admin#show_payments_transactions'
  match '/admins/search_payments_transactions' => "admin#search_payments_transactions"

  match '/student_report' => 'admin#show_student_meetings_reports'
  match '/admins/search_student_meetings_reports' => "admin#search_student_meetings_reports"

  match '/tutor_report' => 'admin#show_tutor_meetings_reports'
  match '/admins/search_tutor_meetings_reports' => "admin#search_tutor_meetings_reports"

  match '/meetings/completed_payment' => 'meetings#completed_payment'
  match '/meetings/cancelled_payment' => 'meetings#cancelled_payment'

  match "auth/:provider/callback" => "admin#oauth"

  match "/search_users" => "users#index"

  match "/tutors/mgmt" => "tutors#mgmt"



  match '/reminder_email_before_twelve_hours' => 'cronjobs#reminder_email_before_twelve_hours'
  match '/reminder_email_before_six_hours' => 'cronjobs#reminder_email_before_six_hours'
  match '/reminder_email_before_two_hours' => 'cronjobs#reminder_email_before_two_hours'
  match '/reminder_email_when_meeting_starts' => 'cronjobs#reminder_email_when_meeting_starts'
  match '/reminder_email_when_meeting_ends' => 'cronjobs#reminder_email_when_meeting_ends'










  root :to => 'pages#index'

  match "/about"=>"pages#about"
  match "/faq"=>"pages#faq"
  match "/comingsoon"=>"pages#comingsoon"
  match "/gettingstarted"=>"pages#gettingstarted"
  match "/howtouse"=>"pages#howtouse"
  match "/contact"=>"pages#contact"
  match "/pricing"=>"pages#pricing"
  match "/team"=>"pages#team"
  match "/press"=>"pages#press"
  match "/tos"=>"pages#terms_and_conditions"
  match "edit_user" => "users#edit"


  
end

app/models/superadmin.rb
class Superadmin < ActiveRecord::Base
  attr_accessible :user_id
  
  belongs_to :user
  validates_uniqueness_of :user_id
end

app/controllers/superadmins_controller.rb
class SuperadminsController < ApplicationController
  # GET /superadmins
  # GET /superadmins.json
  def index
    @superadmins = Superadmin

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @superadmins }
    end
  end

  # GET /superadmins/1
  # GET /superadmins/1.json
  def show
    @superadmin = Superadmin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @superadmin }
    end
  end

  # GET /superadmins/new
  # GET /superadmins/new.json
  def new
    @superadmin = Superadmin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @superadmin }
    end
  end

  # GET /superadmins/1/edit
  def edit
    @superadmin = Superadmin.find(params[:id])
  end

  # POST /superadmins
  # POST /superadmins.json
  def create
    @superadmin = Superadmin.new(params[:superadmin])

    respond_to do |format|
      if @superadmin.save
        format.html { redirect_to @superadmin, notice: 'Superadmin was successfully created.' }
        format.json { render json: @superadmin, status: :created, location: @superadmin }
      else
        format.html { render action: "new" }
        format.json { render json: @superadmin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /superadmins/1
  # PUT /superadmins/1.json
  def update
    @superadmin = Superadmin.find(params[:id])

    respond_to do |format|
      if @superadmin.update_attributes(params[:superadmin])
        format.html { redirect_to @superadmin, notice: 'Superadmin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @superadmin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /superadmins/1
  # DELETE /superadmins/1.json
  def destroy
    @superadmin = Superadmin.find(params[:id])
    @superadmin.destroy

    respond_to do |format|
      format.html { redirect_to superadmins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/superadmins_helper.rb
module SuperadminsHelper
end

app/views/superadmins/_form.html.erb
<%= form_for(@superadmin) do |f| %>
  <% if @superadmin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@superadmin.errors.count, "error") %> prohibited this superadmin from being saved:</h2>

      <ul>
      <% @superadmin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/superadmins/edit.html.erb
<h1>Editing superadmin</h1>

<%= render 'form' %>

<%= link_to 'Show', @superadmin %> |
<%= link_to 'Back', superadmins_path %>

app/views/superadmins/index.html.erb
<h1>Listing superadmins</h1>

<table>
  <tr>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @superadmins.each do |superadmin| %>
  <tr>
    <td><%= superadmin.user_id %></td>
    <td><%= link_to 'Show', superadmin %></td>
    <td><%= link_to 'Edit', edit_superadmin_path(superadmin) %></td>
    <td><%= link_to 'Destroy', superadmin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Superadmin', new_superadmin_path %>

app/views/superadmins/new.html.erb
<h1>New superadmin</h1>

<%= render 'form' %>

<%= link_to 'Back', superadmins_path %>

app/views/superadmins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @superadmin.user_id %>
</p>


<%= link_to 'Edit', edit_superadmin_path(@superadmin) %> |
<%= link_to 'Back', superadmins_path %>