config/routes.rb
Findtutor::Application.routes.draw do
  
  resources :availabilities

  resources :subadmins do
    collection do
      get "generate_free_code"
    end
  end

  resources :departments


  resources :users do
    collection do
      get 'fetch_departments'
    end
  end


  resources :tutor_locations
  resources :universities

  get 'meetings/joinmeeting'
  get 'meetings/createmeeting'
  post 'meetings/ipn_notification'
  get 'meetings/ipn_notification'
  get 'meetings/canceled_payment_request'
  get 'meetings/completed_payment_request'
  post 'meetings/payment'
  get 'meetings/payment_made'
  post 'tutors/addtutor'
  get 'tutors/addtutor'
  get 'tutors/mgmt'
  get 'tutors/approve'
  get 'subjects_tutors/select'
  
  resources :superadmins
  
  resources :tutor_availabilities
  resources :subjects_tutors

  resources :subjects

  get "admin/login"
  post "admin/login"
  get "admin/logout"

  resources :tutors
  

  resources :meetings do
    collection do
      get 'new_meeting'
      get 'end_meeting'
      post 'create_meeting'
    end
  end

  resources :journals do
    collection do
      get 'add_video_to'
    end
  end

  match 'register' => 'users#register'

  match '/payment_transaction' => 'admin#show_payments_transactions'
  match '/admins/search_payments_transactions' => "admin#search_payments_transactions"

  match '/student_report' => 'admin#show_student_meetings_reports'
  match '/admins/search_student_meetings_reports' => "admin#search_student_meetings_reports"

  match '/tutor_report' => 'admin#show_tutor_meetings_reports'
  match '/admins/search_tutor_meetings_reports' => "admin#search_tutor_meetings_reports"

  match '/meetings/completed_payment' => 'meetings#completed_payment'
  match '/meetings/cancelled_payment' => 'meetings#cancelled_payment'

  match "auth/:provider/callback" => "admin#oauth"

  match "/search_users" => "users#index"

  match "/tutors/mgmt" => "tutors#mgmt"



  match '/reminder_email_before_twelve_hours' => 'cronjobs#reminder_email_before_twelve_hours'
  match '/reminder_email_before_six_hours' => 'cronjobs#reminder_email_before_six_hours'
  match '/reminder_email_before_two_hours' => 'cronjobs#reminder_email_before_two_hours'
  match '/reminder_email_when_meeting_starts' => 'cronjobs#reminder_email_when_meeting_starts'
  match '/reminder_email_when_meeting_ends' => 'cronjobs#reminder_email_when_meeting_ends'










  root :to => 'pages#index'

  match "/about"=>"pages#about"
  match "/faq"=>"pages#faq"
  match "/comingsoon"=>"pages#comingsoon"
  match "/gettingstarted"=>"pages#gettingstarted"
  match "/howtouse"=>"pages#howtouse"
  match "/contact"=>"pages#contact"
  match "/pricing"=>"pages#pricing"
  match "/team"=>"pages#team"
  match "/press"=>"pages#press"
  match "/tos"=>"pages#terms_and_conditions"
  match "edit_user" => "users#edit"


  
end

app/models/subadmin.rb
class Subadmin < ActiveRecord::Base
  attr_accessible :user_id

  belongs_to :user
  validates_uniqueness_of :user_id
end

app/controllers/subadmins_controller.rb
class SubadminsController < ApplicationController
  # GET /subadmins
  # GET /subadmins.json
  def index
    @subadmins = Subadmin.paginate(:page => params[:page], :per_page => 30)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subadmins }
    end
  end
  
  def generate_free_code
    @user = User.find_by_id(params[:user_id])
    @free_code = @user.free_codes
    unless @free_code.blank?
      @free_code = @free_code.last.update_attribute(:code , rand(36**10).to_s(36))
      redirect_to subadmins_path
    else
      @free_code = FreeCode.create(:user_id => params[:user_id], :code => rand(36**10).to_s(36))
      redirect_to subadmins_path
    end
  end
  # GET /subadmins/1
  # GET /subadmins/1.json
  def show
    @subadmin = Subadmin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subadmin }
    end
  end

  # GET /subadmins/new
  # GET /subadmins/new.json
  def new
    @subadmin = Subadmin.new

    @users = []
    @usr = User.all
    @usr.each do |usr|
      if usr.usertype == "student"
        @users << usr
      end
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subadmin }
    end
  end

  # GET /subadmins/1/edit
  def edit
    @subadmin = Subadmin.find(params[:id])

    @users = []
    @usr = User.all
    @usr.each do |usr|
      if usr.usertype == "student" || usr.usertype == "subadmin"
        @users << usr
      end
    end

  end

  # POST /subadmins
  # POST /subadmins.json
  def create
    @subadmin = Subadmin.new(params[:subadmin])

    respond_to do |format|
      if @subadmin.save
        format.html { redirect_to @subadmin, notice: 'Subadmin was successfully created.' }
        format.json { render json: @subadmin, status: :created, location: @subadmin }
      else
        format.html { render action: "new" }
        format.json { render json: @subadmin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subadmins/1
  # PUT /subadmins/1.json
  def update
    @subadmin = Subadmin.find(params[:id])

    respond_to do |format|
      if @subadmin.update_attributes(params[:subadmin])
        format.html { redirect_to @subadmin, notice: 'Subadmin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subadmin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subadmins/1
  # DELETE /subadmins/1.json
  def destroy
    @subadmin = Subadmin.find(params[:id])
    @subadmin.destroy

    respond_to do |format|
      format.html { redirect_to subadmins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/subadmins_helper.rb
module SubadminsHelper
end

app/views/subadmins/_form.html.erb
<%= form_for(@subadmin) do |f| %>
  <% if @subadmin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subadmin.errors.count, "error") %> prohibited this subadmin from being saved:</h2>

      <ul>
        <% @subadmin.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.select 'user_id', options_from_collection_for_select(@users, 'id' , "username")%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subadmins/edit.html.erb
<h1>Editing subadmin</h1>

<%= render 'form' %>

<%= link_to 'Show', @subadmin %> |
<%= link_to 'Back', subadmins_path %>

app/views/subadmins/index.html.erb
<h1>Listing subadmins</h1>

<table>
  <tr>
    <th>UserName</th>
    <th>Free Code</th>
    <th></th>
    <th></th>
  </tr>
  <% if @subadmins.present? %>
    <% @subadmins.each do |subadmin| %>
      <tr>
        <td><%= subadmin.user.username %></td>
        <%if subadmin.user.free_codes.blank?%>
          <td><%= link_to 'Generate Code', generate_free_code_subadmins_path(:user_id => subadmin.user) %></td>
        <%else%>
          <%free_code = subadmin.user.free_codes.map(&:code).to_sentence%>
          <td><%= free_code%></td>
          <td><%= link_to 'Regenerate Code', generate_free_code_subadmins_path(:user_id => subadmin.user) %></td>
        <%end%>
        <td><%= link_to 'Show', subadmin %></td>
        <td><%= link_to 'Edit', edit_subadmin_path(subadmin) %></td>
        <td><%= link_to 'Edit Personal', edit_user_path(subadmin.user.id) %></td>
        <td><%= link_to 'Destroy', subadmin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  <% end %>
</table>
<%= will_paginate(@subadmins) %>
<br />

<%= link_to 'New Subadmin', new_subadmin_path %>

app/views/subadmins/new.html.erb
<h1>New subadmin</h1>

<%= render 'form' %>

<%= link_to 'Back', subadmins_path %>

app/views/subadmins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>UserName:</b>
  <%= @subadmin.user.username %>
  <%= link_to "Details", user_path(@subadmin.user) %>
</p>

<%= link_to 'Edit', edit_subadmin_path(@subadmin) %> |
<%= link_to 'Back', subadmins_path %>